LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := migu_shanpao
LOCAL_SRC_FILES := migu_shanpao.apk
#LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_MODULE).apk
#LOCAL_OVERRIDES_PACKAGES :=
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
#LOCAL_PRIVILEGED_MODULE := true
#PRODUCTS.$(INTERNAL_PRODUCT).PRODUCT_PACKAGES += $(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT)/preloadapp
LOCAL_DEX_PREOPT := false
LOCAL_MULTILIB := 32
#JNI_LIBS :=
#$(foreach FILE,$(shell find $(LOCAL_PATH)/lib/ -name *.so), $(eval JNI_LIBS += $(FILE)))
#LOCAL_PREBUILT_JNI_LIBS := $(subst $(LOCAL_PATH),,$(JNI_LIBS))
include $(BUILD_PREBUILT)
